import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { resolveOffer } from '../resolve';
import { validateGiftLines } from '../validateGifts';
import type { GiftValidation } from '../validateGifts';
import type {
  AcrossTierPolicy, Cart, CartLine, ClaimPolicy, GiftPoolEntry, Offer,
  OfferEntitlements, SingleTierResolution, Tier, TriggerMetric, WithinTierPolicy,
} from '../types';

export interface Vector {
  name: string;
  cart: Cart;
  offer: Offer;
  expected: OfferEntitlements;
}

/**
 * The validation family, alongside the entitlement family above. Both are
 * generated by this file and both carry the same staleness guard, but they
 * are written to separate files (`golden.json` / `validation-golden.json`)
 * rather than nested under one JSON document — `golden.json` is already
 * 5.6 MB pretty-printed, and keeping the two families in independent files
 * means a diff, a partial read, or a future JSON Lines migration of one
 * doesn't have to touch the other. `expected` is a plain object, not the
 * `Map` that `validateGiftLines` returns, so this file round-trips through
 * JSON for the Rust side.
 */
export interface ValidationVector {
  name: string;
  cart: Cart;
  offer: Offer;
  expected: Record<string, GiftValidation>;
}

type AcrossSpec = { acrossTiers: AcrossTierPolicy; singleResolution?: SingleTierResolution };

const WITHIN: WithinTierPolicy[] = ['ALL_IN_POOL', 'PICK_ONE'];
const ACROSS: AcrossSpec[] = [
  { acrossTiers: 'STACK' },
  { acrossTiers: 'SINGLE', singleResolution: 'HIGHEST' },
  { acrossTiers: 'SINGLE', singleResolution: 'PINNED' },
  { acrossTiers: 'SINGLE', singleResolution: 'CUSTOMER_CHOICE' },
];
const TIER_COUNTS = [1, 2, 3, 4, 5, 6];
const TRIGGERS: TriggerMetric[] = ['SUBTOTAL', 'QUANTITY'];

/** Shared gift-pool-entry builder. Defaults to FREE, as most pool entries are. */
function gift(variantId: string, over: Partial<GiftPoolEntry> = {}): GiftPoolEntry {
  return { variantId, discountType: 'FREE', value: 0, maxQty: 1, ...over };
}

/** A single non-gift line contributing `unitPrice` to whatever offers are in `inScope`. */
function line(id: string, unitPrice: number, inScope: string[], over: Partial<CartLine> = {}): CartLine {
  return { id, quantity: 1, unitPrice, variantId: `${id}-variant`, inScope, ...over };
}

// ---------------------------------------------------------------------------
// Family 1 — the original policy matrix. Enumerates claim-policy combinations
// while holding tier *shape* mostly fixed (FREE_SHIPPING first tier, GIFT
// tiers after). This is necessary coverage but not sufficient — see the
// families below, which vary the data the policy matrix held fixed.
// ---------------------------------------------------------------------------

function buildOffer(
  tierCount: number,
  within: WithinTierPolicy,
  across: AcrossSpec,
  trigger: TriggerMetric
): Offer {
  const tiers = Array.from({ length: tierCount }, (_, i) => ({
    id: `t${i + 1}`,
    threshold: trigger === 'QUANTITY' ? (i + 1) * 2 : (i + 1) * 5000,
    reward: (i === 0 ? 'FREE_SHIPPING' : 'GIFT') as Offer['tiers'][number]['reward'],
    giftPool:
      i === 0
        ? []
        : Array.from({ length: (i % 3) + 1 }, (_, g) => ({
            variantId: `v${i}-${g}`,
            discountType: 'FREE' as const,
            value: 0,
            maxQty: (g % 2) + 1,
          })),
  }));

  const claimPolicy: ClaimPolicy = {
    withinTier: within,
    acrossTiers: across.acrossTiers,
    ...(across.singleResolution ? { singleResolution: across.singleResolution } : {}),
    ...(across.singleResolution === 'PINNED' ? { pinnedTierId: 't2' } : {}),
  };

  return { id: 'o1', trigger, claimPolicy, tiers };
}

/** Below, exactly at, and above every threshold, plus zero. */
function measurePoints(offer: Offer): number[] {
  const points = new Set<number>([0]);
  for (const t of offer.tiers) {
    if (t.threshold > 0) points.add(t.threshold - 1);
    points.add(t.threshold);
    points.add(t.threshold + 1);
  }
  return [...points].sort((a, b) => a - b);
}

function buildCart(measure: number, trigger: TriggerMetric, withGift: boolean): Cart {
  const lines: Cart['lines'] = [];
  if (measure > 0) {
    lines.push(
      trigger === 'QUANTITY'
        ? { id: 'l1', quantity: measure, unitPrice: 1000, variantId: 'base', inScope: ['o1'] }
        : { id: 'l1', quantity: 1, unitPrice: measure, variantId: 'base', inScope: ['o1'] }
    );
  }
  if (withGift) {
    lines.push({
      id: 'lg', quantity: 1, unitPrice: 4000, variantId: 'v1-0',
      inScope: ['o1'], giftOfferId: 'o1', giftTierId: 't2',
    });
  }
  return { lines };
}

function generatePolicyMatrixVectors(): Vector[] {
  const vectors: Vector[] = [];
  for (const trigger of TRIGGERS) {
    for (const within of WITHIN) {
      for (const across of ACROSS) {
        for (const tierCount of TIER_COUNTS) {
          const offer = buildOffer(tierCount, within, across, trigger);
          for (const measure of measurePoints(offer)) {
            for (const withGift of [false, true]) {
              const cart = buildCart(measure, trigger, withGift);
              const suffix = across.singleResolution ?? across.acrossTiers;
              vectors.push({
                name: `policy/${trigger}/${within}/${suffix}/tiers=${tierCount}/measure=${measure}/gift=${withGift}`,
                cart,
                offer,
                expected: resolveOffer(cart, offer),
              });
            }
          }
        }
      }
    }
  }
  return vectors;
}

// ---------------------------------------------------------------------------
// Family 2 — reward-shape axis. The policy matrix above only ever put GIFT
// tiers after a single FREE_SHIPPING tier, so orderPercent/orderFixed were 0
// in every one of its vectors. This crosses three tier *shapes* — all-gift,
// mixed reward kinds, and an order-discount ladder with two ORDER_PERCENT
// tiers and two ORDER_FIXED tiers at different values — against STACK and
// all three SINGLE resolutions, pinning both the "highest single value per
// type, never accumulate" rule and its independence from the claim policy
// (order/shipping rewards come from ALL unlocked tiers, not the tiers the
// claim policy chose to grant gifts from).
// ---------------------------------------------------------------------------

type RewardShapeName = 'all-gift' | 'mixed' | 'order-ladder';

function rewardShapeTiers(shape: RewardShapeName): Tier[] {
  switch (shape) {
    case 'all-gift':
      return [
        { id: 'rs-g1', threshold: 5000, reward: 'GIFT', giftPool: [gift('rs-g1-v0'), gift('rs-g1-v1')] },
        { id: 'rs-g2', threshold: 10000, reward: 'GIFT', giftPool: [gift('rs-g2-v0')] },
        { id: 'rs-g3', threshold: 15000, reward: 'GIFT', giftPool: [gift('rs-g3-v0'), gift('rs-g3-v1'), gift('rs-g3-v2')] },
      ];
    case 'mixed':
      return [
        { id: 'rs-m1', threshold: 5000, reward: 'FREE_SHIPPING', giftPool: [] },
        { id: 'rs-m2', threshold: 10000, reward: 'GIFT', giftPool: [gift('rs-m2-v0'), gift('rs-m2-v1')] },
        { id: 'rs-m3', threshold: 15000, reward: 'ORDER_PERCENT', value: 15, giftPool: [] },
        { id: 'rs-m4', threshold: 20000, reward: 'ORDER_FIXED', value: 1000, giftPool: [] },
      ];
    case 'order-ladder':
      // Two ORDER_PERCENT tiers at different values, two ORDER_FIXED tiers at
      // different values. No GIFT tiers at all — this shape exists purely to
      // pin non-accumulation, independent of any gift claiming.
      return [
        { id: 'rs-o1', threshold: 5000, reward: 'ORDER_PERCENT', value: 10, giftPool: [] },
        { id: 'rs-o2', threshold: 10000, reward: 'ORDER_PERCENT', value: 25, giftPool: [] },
        { id: 'rs-o3', threshold: 15000, reward: 'ORDER_FIXED', value: 500, giftPool: [] },
        { id: 'rs-o4', threshold: 20000, reward: 'ORDER_FIXED', value: 2000, giftPool: [] },
      ];
  }
}

/** The tier a PINNED policy targets for this shape — irrelevant when the shape has no GIFT tier. */
function pinnedTargetFor(shape: RewardShapeName): string {
  switch (shape) {
    case 'all-gift': return 'rs-g2';
    case 'mixed': return 'rs-m2';
    case 'order-ladder': return 'rs-o1';
  }
}

function rewardShapeOffer(shape: RewardShapeName, across: AcrossSpec): Offer {
  const tiers = rewardShapeTiers(shape);
  const claimPolicy: ClaimPolicy = {
    withinTier: 'PICK_ONE',
    acrossTiers: across.acrossTiers,
    ...(across.singleResolution ? { singleResolution: across.singleResolution } : {}),
    ...(across.singleResolution === 'PINNED' ? { pinnedTierId: pinnedTargetFor(shape) } : {}),
  };
  return { id: 'o1', trigger: 'SUBTOTAL', claimPolicy, tiers };
}

function generateRewardShapeVectors(): Vector[] {
  const vectors: Vector[] = [];
  const shapes: RewardShapeName[] = ['all-gift', 'mixed', 'order-ladder'];
  for (const shape of shapes) {
    for (const across of ACROSS) {
      const offer = rewardShapeOffer(shape, across);
      const suffix = across.singleResolution ?? across.acrossTiers;
      for (const measure of measurePoints(offer)) {
        const cart = buildCart(measure, 'SUBTOTAL', false);
        vectors.push({
          name: `rewardShape/${shape}/${suffix}/measure=${measure}`,
          cart,
          offer,
          expected: resolveOffer(cart, offer),
        });
      }
    }
  }
  return vectors;
}

// ---------------------------------------------------------------------------
// Family 3 — inScope variation. Every vector in the policy matrix scoped its
// one line to `['o1']`. This varies scope directly: in scope, out of scope
// (empty array), scoped to a different offer id, and mixes of these, plus a
// line scoped to more than one offer at once.
// ---------------------------------------------------------------------------

function generateInScopeVectors(): Vector[] {
  const offer: Offer = {
    id: 'o1',
    trigger: 'SUBTOTAL',
    claimPolicy: { withinTier: 'PICK_ONE', acrossTiers: 'STACK' },
    tiers: [{ id: 'is-t1', threshold: 5000, reward: 'GIFT', giftPool: [gift('is-t1-v0')] }],
  };

  const scenarios: Array<{ suffix: string; lines: CartLine[] }> = [
    { suffix: 'in-scope-only', lines: [line('l1', 6000, ['o1'])] },
    { suffix: 'out-of-scope-only', lines: [line('l1', 6000, [])] },
    { suffix: 'scoped-to-other-offer-only', lines: [line('l1', 6000, ['o2'])] },
    { suffix: 'mixed-in-and-unscoped', lines: [line('l1', 3000, ['o1']), line('l2', 9000, [])] },
    { suffix: 'mixed-in-and-other-offer', lines: [line('l1', 3000, ['o1']), line('l2', 9000, ['o2'])] },
    { suffix: 'line-scoped-to-multiple-offers', lines: [line('l1', 6000, ['o1', 'o2'])] },
  ];

  return scenarios.map(({ suffix, lines }) => {
    const cart: Cart = { lines };
    return {
      name: `inScope/${suffix}`,
      cart,
      offer,
      expected: resolveOffer(cart, offer),
    };
  });
}

// ---------------------------------------------------------------------------
// Family 4 — pinnedTierId variation. Task 16 made every miss fail closed
// (grant nothing); these four vectors pin each distinct miss shape so a
// regression toward the old "fall back to HIGHEST" behaviour is caught, and
// so a fix that only closes one of the two miss cases (unknown id vs. absent
// id) is caught too.
// ---------------------------------------------------------------------------

function generatePinnedVectors(): Vector[] {
  const tiers: Tier[] = [
    { id: 'pin-t1', threshold: 5000, reward: 'GIFT', giftPool: [gift('pin-t1-v0')] },
    { id: 'pin-t2', threshold: 10000, reward: 'GIFT', giftPool: [gift('pin-t2-v0')] },
  ];

  const offerWith = (pinnedTierId: string | undefined): Offer => ({
    id: 'o1',
    trigger: 'SUBTOTAL',
    claimPolicy: {
      withinTier: 'PICK_ONE',
      acrossTiers: 'SINGLE',
      singleResolution: 'PINNED',
      ...(pinnedTierId !== undefined ? { pinnedTierId } : {}),
    },
    tiers,
  });

  const scenarios: Array<{ suffix: string; pinnedTierId: string | undefined; measure: number }> = [
    { suffix: 'valid-and-unlocked', pinnedTierId: 'pin-t2', measure: 12000 },
    { suffix: 'valid-but-locked-while-lower-tier-unlocked', pinnedTierId: 'pin-t2', measure: 6000 },
    { suffix: 'unknown-id', pinnedTierId: 'does-not-exist', measure: 12000 },
    { suffix: 'absent', pinnedTierId: undefined, measure: 12000 },
  ];

  return scenarios.map(({ suffix, pinnedTierId, measure }) => {
    const offer = offerWith(pinnedTierId);
    const cart = buildCart(measure, 'SUBTOTAL', false);
    return {
      name: `pinned/${suffix}`,
      cart,
      offer,
      expected: resolveOffer(cart, offer),
    };
  });
}

// ---------------------------------------------------------------------------
// Family 5 — multi-offer carts. Pins the cross-offer gift-exclusion rule in
// subtotal.ts: a line tagged as *any* offer's gift — this offer's own, or a
// different offer's — never contributes to a qualifying measure.
// ---------------------------------------------------------------------------

function generateMultiOfferVectors(): Vector[] {
  const offerO1: Offer = {
    id: 'o1',
    trigger: 'SUBTOTAL',
    claimPolicy: { withinTier: 'PICK_ONE', acrossTiers: 'STACK' },
    tiers: [{ id: 'mo-t1', threshold: 5000, reward: 'GIFT', giftPool: [gift('mo-t1-v0')] }],
  };

  const scenarios: Array<{ suffix: string; lines: CartLine[] }> = [
    {
      suffix: 'other-offers-gift-excluded',
      lines: [
        line('l1', 6000, ['o1']),
        { id: 'lg', quantity: 1, unitPrice: 4000, variantId: 'mo-t1-v0', inScope: ['o1'], giftOfferId: 'o2', giftTierId: 'other-offer-tier' },
      ],
    },
    {
      suffix: 'own-offers-gift-excluded',
      lines: [
        line('l1', 6000, ['o1']),
        { id: 'lg', quantity: 1, unitPrice: 4000, variantId: 'mo-t1-v0', inScope: ['o1'], giftOfferId: 'o1', giftTierId: 'mo-t1' },
      ],
    },
    {
      suffix: 'two-offers-gifts-both-excluded',
      lines: [
        line('l1', 6000, ['o1']),
        { id: 'lg1', quantity: 1, unitPrice: 2000, variantId: 'x', inScope: ['o1'], giftOfferId: 'o1', giftTierId: 'mo-t1' },
        { id: 'lg2', quantity: 1, unitPrice: 3000, variantId: 'y', inScope: ['o1'], giftOfferId: 'o2', giftTierId: 'z' },
      ],
    },
  ];

  return scenarios.map(({ suffix, lines }) => {
    const cart: Cart = { lines };
    return {
      name: `multiOffer/${suffix}`,
      cart,
      offer: offerO1,
      expected: resolveOffer(cart, offerO1),
    };
  });
}

// ---------------------------------------------------------------------------
// Family 6 — tier ordering and ties. `unlockedTiers` sorts ascending by
// threshold regardless of config order, and JS's stable sort happens to
// preserve config order among ties — but Rust's `sort_unstable` is free to
// differ. These vectors pin config order as the tie-break (not sort
// stability, not tier id, not the config array's raw filter order for the
// unsorted case), for both STACK and SINGLE:HIGHEST.
// ---------------------------------------------------------------------------

function tierOrderOffer(tiers: Tier[], across: AcrossSpec): Offer {
  const claimPolicy: ClaimPolicy = {
    withinTier: 'PICK_ONE',
    acrossTiers: across.acrossTiers,
    ...(across.singleResolution ? { singleResolution: across.singleResolution } : {}),
  };
  return { id: 'o1', trigger: 'SUBTOTAL', claimPolicy, tiers };
}

function generateTierOrderVectors(): Vector[] {
  const vectors: Vector[] = [];
  const acrossForOrder: AcrossSpec[] = [
    { acrossTiers: 'STACK' },
    { acrossTiers: 'SINGLE', singleResolution: 'HIGHEST' },
  ];

  // Config order does not match threshold order. unlockedTierIds must still
  // come out sorted ascending by threshold, and SINGLE:HIGHEST must pick the
  // tier with the highest *threshold*, not the last entry in the config array
  // (whose last entry, ord-t2 at 10000, is not the highest).
  const unsortedTiers: Tier[] = [
    { id: 'ord-t3', threshold: 15000, reward: 'GIFT', giftPool: [gift('ord-t3-v0')] },
    { id: 'ord-t1', threshold: 5000, reward: 'GIFT', giftPool: [gift('ord-t1-v0')] },
    { id: 'ord-t2', threshold: 10000, reward: 'GIFT', giftPool: [gift('ord-t2-v0')] },
  ];
  for (const across of acrossForOrder) {
    const offer = tierOrderOffer(unsortedTiers, across);
    const suffix = across.singleResolution ?? across.acrossTiers;
    for (const measure of [4999, 5000, 12000, 20000]) {
      const cart = buildCart(measure, 'SUBTOTAL', false);
      vectors.push({
        name: `tierOrder/unsorted-config/${suffix}/measure=${measure}`,
        cart,
        offer,
        expected: resolveOffer(cart, offer),
      });
    }
  }

  // Two tiers share a threshold. Config order is 'tie-a' then 'tie-b'.
  const tiedAB: Tier[] = [
    { id: 'tie-a', threshold: 10000, reward: 'GIFT', giftPool: [gift('tie-a-v0')] },
    { id: 'tie-b', threshold: 10000, reward: 'GIFT', giftPool: [gift('tie-b-v0')] },
  ];
  // Same tie, reversed config order — proves the tie-break follows config
  // order rather than tier id (which would put tie-a first either way).
  const tiedBA: Tier[] = [
    { id: 'tie-b', threshold: 10000, reward: 'GIFT', giftPool: [gift('tie-b-v0')] },
    { id: 'tie-a', threshold: 10000, reward: 'GIFT', giftPool: [gift('tie-a-v0')] },
  ];
  // A three-way tie.
  const tripleTied: Tier[] = [
    { id: 'tie3-x', threshold: 8000, reward: 'GIFT', giftPool: [gift('tie3-x-v0')] },
    { id: 'tie3-y', threshold: 8000, reward: 'GIFT', giftPool: [gift('tie3-y-v0')] },
    { id: 'tie3-z', threshold: 8000, reward: 'GIFT', giftPool: [gift('tie3-z-v0')] },
  ];

  const tieCases: Array<{ label: string; tiers: Tier[]; measure: number }> = [
    { label: 'tied-threshold-a-before-b', tiers: tiedAB, measure: 10000 },
    { label: 'tied-threshold-b-before-a', tiers: tiedBA, measure: 10000 },
    { label: 'triple-tie', tiers: tripleTied, measure: 8000 },
  ];
  for (const { label, tiers, measure } of tieCases) {
    for (const across of acrossForOrder) {
      const offer = tierOrderOffer(tiers, across);
      const suffix = across.singleResolution ?? across.acrossTiers;
      const cart = buildCart(measure, 'SUBTOTAL', false);
      vectors.push({
        name: `tierOrder/${label}/${suffix}`,
        cart,
        offer,
        expected: resolveOffer(cart, offer),
      });
    }
  }

  return vectors;
}

// ---------------------------------------------------------------------------
// Family 7 — remaining shapes: a GIFT tier with an empty pool (unlocked but
// grants nothing), a zero-threshold tier (unlocked even for an empty cart),
// and gift pool entries using PERCENT and FIXED discount types rather than
// only FREE.
// ---------------------------------------------------------------------------

function generateRemainingShapeVectors(): Vector[] {
  const vectors: Vector[] = [];

  const emptyPoolOffer: Offer = {
    id: 'o1',
    trigger: 'SUBTOTAL',
    claimPolicy: { withinTier: 'PICK_ONE', acrossTiers: 'STACK' },
    tiers: [{ id: 'empty-t1', threshold: 5000, reward: 'GIFT', giftPool: [] }],
  };
  for (const measure of [4999, 5000, 9000]) {
    const cart = buildCart(measure, 'SUBTOTAL', false);
    vectors.push({
      name: `shapes/empty-gift-pool/measure=${measure}`,
      cart,
      offer: emptyPoolOffer,
      expected: resolveOffer(cart, emptyPoolOffer),
    });
  }

  const zeroThresholdOffer: Offer = {
    id: 'o1',
    trigger: 'SUBTOTAL',
    claimPolicy: { withinTier: 'ALL_IN_POOL', acrossTiers: 'STACK' },
    tiers: [
      { id: 'zero-t0', threshold: 0, reward: 'GIFT', giftPool: [gift('zero-t0-v0')] },
      { id: 'zero-t1', threshold: 5000, reward: 'GIFT', giftPool: [gift('zero-t1-v0')] },
    ],
  };
  for (const measure of [0, 4999, 5000]) {
    const cart = buildCart(measure, 'SUBTOTAL', false);
    vectors.push({
      name: `shapes/zero-threshold/measure=${measure}`,
      cart,
      offer: zeroThresholdOffer,
      expected: resolveOffer(cart, zeroThresholdOffer),
    });
  }

  const discountTypeOffer: Offer = {
    id: 'o1',
    trigger: 'SUBTOTAL',
    claimPolicy: { withinTier: 'ALL_IN_POOL', acrossTiers: 'STACK' },
    tiers: [
      {
        id: 'dt-t1',
        threshold: 5000,
        reward: 'GIFT',
        giftPool: [
          gift('dt-free', { discountType: 'FREE', value: 0 }),
          gift('dt-percent', { discountType: 'PERCENT', value: 50 }),
          gift('dt-fixed', { discountType: 'FIXED', value: 1500 }),
        ],
      },
    ],
  };
  {
    const cart = buildCart(6000, 'SUBTOTAL', false);
    vectors.push({
      name: 'shapes/gift-discount-types',
      cart,
      offer: discountTypeOffer,
      expected: resolveOffer(cart, discountTypeOffer),
    });
  }

  return vectors;
}

export function generateVectors(): Vector[] {
  return [
    ...generatePolicyMatrixVectors(),
    ...generateRewardShapeVectors(),
    ...generateInScopeVectors(),
    ...generatePinnedVectors(),
    ...generateMultiOfferVectors(),
    ...generateTierOrderVectors(),
    ...generateRemainingShapeVectors(),
  ];
}

// ---------------------------------------------------------------------------
// Validation vector family (Task 18). validateGiftLines is a cart-level
// function with no vectors at all before this — the function that decides
// whether a merchant loses inventory, entirely unconstrained by the parity
// contract. Each vector captures { cart, offer } -> the full validation map,
// serialised as a plain object so it round-trips through JSON for Rust.
// ---------------------------------------------------------------------------

/** t-v1 unlocks at 10000 with a three-entry pool; t-v2 unlocks at 15000 with one entry. */
const validationOffer = (over: Partial<Offer> = {}): Offer => ({
  id: 'o1',
  trigger: 'SUBTOTAL',
  claimPolicy: { withinTier: 'PICK_ONE', acrossTiers: 'STACK' },
  tiers: [
    { id: 'v-t1', threshold: 10000, reward: 'GIFT', giftPool: [gift('v-mug'), gift('v-tote'), gift('v-candle')] },
    { id: 'v-t2', threshold: 15000, reward: 'GIFT', giftPool: [gift('v-hoodie')] },
  ],
  ...over,
});

const spendLine = (id: string, amount: number): CartLine => ({
  id, quantity: 1, unitPrice: amount, variantId: 'spend', inScope: ['o1'],
});

const claimLine = (id: string, variantId: string, over: Partial<CartLine> = {}): CartLine => ({
  id, quantity: 1, unitPrice: 4000, variantId, inScope: ['o1'],
  giftOfferId: 'o1', giftTierId: 'v-t1', ...over,
});

function buildValidationVector(name: string, cart: Cart, offer: Offer): ValidationVector {
  return {
    name,
    cart,
    offer,
    expected: Object.fromEntries(validateGiftLines(cart, offer)),
  };
}

export function generateValidationVectors(): ValidationVector[] {
  const vectors: ValidationVector[] = [];

  // A genuine, uncontested claim.
  vectors.push(
    buildValidationVector(
      'validation/genuine-claim',
      { lines: [spendLine('l1', 16000), claimLine('lg', 'v-mug')] },
      validationOffer()
    )
  );

  // A forged variant — not a member of any pool.
  vectors.push(
    buildValidationVector(
      'validation/forged-variant-not-in-any-pool',
      { lines: [spendLine('l1', 16000), claimLine('lg', 'not-in-any-pool')] },
      validationOffer()
    )
  );

  // A claim on a tier that is not unlocked.
  vectors.push(
    buildValidationVector(
      'validation/claim-on-locked-tier',
      { lines: [spendLine('l1', 11000), claimLine('lg', 'v-hoodie', { giftTierId: 'v-t2' })] },
      validationOffer()
    )
  );

  // A claim naming a tier id that does not exist in the offer at all.
  vectors.push(
    buildValidationVector(
      'validation/claim-on-unknown-tier',
      { lines: [spendLine('l1', 16000), claimLine('lg', 'v-mug', { giftTierId: 'does-not-exist' })] },
      validationOffer()
    )
  );

  // Under SINGLE:HIGHEST both tiers are unlocked but only the highest grants;
  // the claim names the lower, unlocked-but-non-granting tier.
  vectors.push(
    buildValidationVector(
      'validation/single-highest-non-granting-tier',
      { lines: [spendLine('l1', 16000), claimLine('lg', 'v-mug', { giftTierId: 'v-t1' })] },
      validationOffer({
        claimPolicy: { withinTier: 'PICK_ONE', acrossTiers: 'SINGLE', singleResolution: 'HIGHEST' },
      })
    )
  );

  // A claim naming a different offer than the one being validated.
  vectors.push(
    buildValidationVector(
      'validation/claim-on-different-offer',
      { lines: [spendLine('l1', 16000), claimLine('lg', 'v-mug', { giftOfferId: 'o2' })] },
      validationOffer()
    )
  );

  // quantity > maxQty (default maxQty is 1).
  vectors.push(
    buildValidationVector(
      'validation/quantity-above-maxQty',
      { lines: [spendLine('l1', 16000), claimLine('lg', 'v-mug', { quantity: 5 })] },
      validationOffer()
    )
  );

  const maxQtyThreeOffer = validationOffer({
    tiers: [{ id: 'v-t1', threshold: 10000, reward: 'GIFT', giftPool: [gift('v-mug', { maxQty: 3 })] }],
  });

  // quantity < maxQty — discounts exactly what is present, not the full budget.
  vectors.push(
    buildValidationVector(
      'validation/quantity-below-maxQty',
      { lines: [spendLine('l1', 16000), claimLine('lg', 'v-mug', { quantity: 2 })] },
      maxQtyThreeOffer
    )
  );

  // maxQty > 1, quantity meets it exactly.
  vectors.push(
    buildValidationVector(
      'validation/maxQty-greater-than-one-exact-match',
      { lines: [spendLine('l1', 16000), claimLine('lg', 'v-mug', { quantity: 3 })] },
      maxQtyThreeOffer
    )
  );

  // Multiple lines claiming the SAME pool entry: maxQty is a budget summed
  // across lines, not a per-line cap. ALL_IN_POOL is used so the one-claim-
  // per-tier rule doesn't also apply here — this isolates the maxQty budget
  // mechanism specifically.
  const singleUnitOffer = validationOffer({
    claimPolicy: { withinTier: 'ALL_IN_POOL', acrossTiers: 'STACK' },
    tiers: [{ id: 'v-t1', threshold: 10000, reward: 'GIFT', giftPool: [gift('v-mug', { maxQty: 1 })] }],
  });
  vectors.push(
    buildValidationVector(
      'validation/maxQty-budget-shared-across-lines',
      {
        lines: [
          spendLine('l1', 16000),
          claimLine('la', 'v-mug'),
          claimLine('lb', 'v-mug'),
          claimLine('lc', 'v-mug'),
        ],
      },
      singleUnitOffer
    )
  );

  // Multiple lines claiming DIFFERENT members of one PICK_ONE pool: the
  // highest-value claim wins, the rest bill at full price.
  vectors.push(
    buildValidationVector(
      'validation/pick-one-arbitration-highest-value-wins',
      {
        lines: [
          spendLine('l1', 16000),
          claimLine('lm', 'v-mug', { unitPrice: 4000 }),
          claimLine('lt', 'v-tote', { unitPrice: 3000 }),
          claimLine('lc', 'v-candle', { unitPrice: 1000 }),
        ],
      },
      validationOffer()
    )
  );

  // A value tie between two competing claims resolves to the lower line id,
  // byte-lexicographic ascending — not array/claim order.
  vectors.push(
    buildValidationVector(
      'validation/value-tie-resolved-by-line-id',
      {
        lines: [
          spendLine('l1', 16000),
          claimLine('lz', 'v-mug', { unitPrice: 4000 }),
          claimLine('la', 'v-tote', { unitPrice: 4000 }),
        ],
      },
      validationOffer()
    )
  );

  // Contrast case: ALL_IN_POOL has no one-claim-per-tier budget, so every
  // distinct pool entry claimed is granted simultaneously.
  vectors.push(
    buildValidationVector(
      'validation/all-in-pool-grants-every-distinct-entry',
      {
        lines: [
          spendLine('l1', 16000),
          claimLine('lm', 'v-mug'),
          claimLine('lt', 'v-tote'),
          claimLine('lc', 'v-candle'),
        ],
      },
      validationOffer({ claimPolicy: { withinTier: 'ALL_IN_POOL', acrossTiers: 'STACK' } })
    )
  );

  // A line with no gift attributes at all never appears in the result map.
  vectors.push(
    buildValidationVector(
      'validation/plain-line-absent-from-map',
      {
        lines: [
          spendLine('l1', 16000),
          { id: 'lp', quantity: 1, unitPrice: 4000, variantId: 'v-mug', inScope: ['o1'] },
        ],
      },
      validationOffer()
    )
  );

  // claimValue's PERCENT branch only matters when flooring vs rounding
  // flips which claim wins. 'lz' claims a PERCENT-50%... no: PERCENT
  // value:10 on unitPrice:105 -> floor(105*10/100) = floor(10.5) = 10.
  // 'la' claims FIXED value:10 on unitPrice:1000 -> min(10, 1000) = 10,
  // same either way. Flooring ties both claims at 10, and the id tie-break
  // (byte-lexicographic ascending) picks 'la' since 'la' < 'lz'. A mutant
  // that rounds instead — (unitPrice * value + 50) / 100 with integer
  // division — computes (1050 + 50) / 100 = 11 for 'lz', which then wins
  // outright instead of losing the tie. Different winner, not just a
  // different number, so this vector discriminates flooring from rounding.
  vectors.push(
    buildValidationVector(
      'validation/percent-floor-vs-round-tie-break',
      {
        lines: [
          spendLine('l1', 16000),
          claimLine('lz', 'round-percent', { unitPrice: 105 }),
          claimLine('la', 'round-fixed', { unitPrice: 1000 }),
        ],
      },
      validationOffer({
        tiers: [
          {
            id: 'v-t1',
            threshold: 10000,
            reward: 'GIFT',
            giftPool: [
              gift('round-percent', { discountType: 'PERCENT', value: 10 }),
              gift('round-fixed', { discountType: 'FIXED', value: 10 }),
            ],
          },
        ],
      })
    )
  );

  // A zero- or negative-quantity claim must not consume the tier's PICK_ONE
  // budget — a line with nothing on it cannot receive a discount, and must
  // not crowd out a real line that could have used that budget. Three lines
  // claim three distinct entries in the same PICK_ONE tier: 'lreal' has
  // quantity 1 and the lowest claim value (3000, FREE == unitPrice);
  // 'lzero' has quantity 0 and a higher value (9000); 'lneg' has quantity
  // -2 and the highest value (12000). With the `quantity <= 0` guard, both
  // 'lzero' and 'lneg' are excluded before arbitration and 'lreal' wins the
  // tier's one slot. Without the guard, 'lneg' sorts first by value, wins
  // the slot with a nonsensical negative discountQuantity, and 'lreal' is
  // rejected outright even though it is the only line with anything to
  // discount.
  vectors.push(
    buildValidationVector(
      'validation/nonpositive-quantity-does-not-consume-budget',
      {
        lines: [
          spendLine('l1', 16000),
          claimLine('lreal', 'zq-real', { unitPrice: 3000, quantity: 1 }),
          claimLine('lzero', 'zq-zero', { unitPrice: 9000, quantity: 0 }),
          claimLine('lneg', 'zq-neg', { unitPrice: 12000, quantity: -2 }),
        ],
      },
      validationOffer({
        tiers: [
          {
            id: 'v-t1',
            threshold: 10000,
            reward: 'GIFT',
            giftPool: [
              gift('zq-real', { discountType: 'FREE', value: 0 }),
              gift('zq-zero', { discountType: 'FREE', value: 0 }),
              gift('zq-neg', { discountType: 'FREE', value: 0 }),
            ],
          },
        ],
      })
    )
  );

  return vectors;
}

if (process.argv[1]?.endsWith('generate.ts')) {
  const vectors = generateVectors();
  writeFileSync(
    join(import.meta.dirname, 'golden.json'),
    JSON.stringify(vectors, null, 2) + '\n'
  );
  console.log(`Wrote ${vectors.length} entitlement vectors`);

  const validationVectors = generateValidationVectors();
  writeFileSync(
    join(import.meta.dirname, 'validation-golden.json'),
    JSON.stringify(validationVectors, null, 2) + '\n'
  );
  console.log(`Wrote ${validationVectors.length} validation vectors`);
}
