import { describe, it, expect } from 'vitest';
import {
  encodeConfig,
  encodeId,
  encodeOffer,
  encodeSharded,
  serializeConfig,
  shardCompactOffers,
  byteLength,
  ACROSS_TIER_CODES,
  COLLECTION_GID_PREFIX,
  GIFT_DISCOUNT_CODES,
  MAX_SHARDS,
  PRODUCT_GID_PREFIX,
  REWARD_CODES,
  SCOPE_KIND_CODES,
  SINGLE_RESOLUTION_CODES,
  TRIGGER_CODES,
  VARIANT_GID_PREFIX,
  WITHIN_TIER_CODES,
  type FunctionOffer,
} from './encode';

function offer(over: Partial<FunctionOffer> = {}): FunctionOffer {
  return {
    id: 'o1',
    trigger: 'SUBTOTAL',
    claimPolicy: { withinTier: 'ALL_IN_POOL', acrossTiers: 'STACK' },
    tiers: [{ id: 't1', threshold: 5000, reward: 'FREE_SHIPPING', giftPool: [] }],
    scope: { kind: 'ENTIRE_CART', ids: [] },
    audience: { customerTags: [], markets: [] },
    ...over,
  };
}

/**
 * These are the only assertions in the suite written by hand rather than
 * derived from the encoder. `encoding-golden.json` is generated by
 * `encodeConfig`, so it cannot by itself catch a change to what `encodeConfig`
 * produces — it can only catch the two languages drifting apart. These literal
 * expectations are the other half: they fail if the wire format changes at
 * all, which is what makes such a change a deliberate, versioned decision.
 */
describe('the wire format, asserted literally', () => {
  it('encodes a minimal offer to the documented bytes', () => {
    expect(serializeConfig(encodeConfig([offer()]))).toBe(
      '{"v":1,"o":[{"i":"o1","t":0,"w":0,"a":0,"r":[{"i":"t1","t":5000,"r":0}]}]}'
    );
  });

  it('encodes every field of a fully-populated offer to the documented bytes', () => {
    const full = offer({
      id: 'o9',
      trigger: 'QUANTITY',
      claimPolicy: {
        withinTier: 'PICK_ONE',
        acrossTiers: 'SINGLE',
        singleResolution: 'CUSTOMER_CHOICE',
        pinnedTierId: 't2',
      },
      scope: { kind: 'PRODUCTS', ids: [`${PRODUCT_GID_PREFIX}7000001`] },
      audience: { customerTags: ['vip'], markets: ['US'] },
      tiers: [
        {
          id: 't2',
          threshold: 3,
          reward: 'GIFT',
          value: 25,
          giftPool: [
            {
              variantId: `${VARIANT_GID_PREFIX}1000000000000`,
              discountType: 'PERCENT',
              value: 50,
              maxQty: 2,
            },
          ],
        },
      ],
    });

    expect(serializeConfig(encodeConfig([full]))).toBe(
      '{"v":1,"o":[{"i":"o9","t":1,"w":1,"a":1,"s":2,"p":"t2","y":2,"c":[7000001],' +
        '"x":["vip"],"m":["US"],"r":[{"i":"t2","t":3,"r":3,"v":25,' +
        '"g":[[1000000000000,1,50,2]]}]}]}'
    );
  });

  it('pins the enum wire codes', () => {
    // The one rule that is never negotiable: these integers are live in
    // merchants' shops. Appending is safe; reordering silently reinterprets
    // every published config.
    expect(TRIGGER_CODES).toEqual(['SUBTOTAL', 'QUANTITY']);
    expect(REWARD_CODES).toEqual(['FREE_SHIPPING', 'ORDER_PERCENT', 'ORDER_FIXED', 'GIFT']);
    expect(GIFT_DISCOUNT_CODES).toEqual(['FREE', 'PERCENT', 'FIXED']);
    expect(WITHIN_TIER_CODES).toEqual(['ALL_IN_POOL', 'PICK_ONE']);
    expect(ACROSS_TIER_CODES).toEqual(['STACK', 'SINGLE']);
    expect(SINGLE_RESOLUTION_CODES).toEqual(['HIGHEST', 'PINNED', 'CUSTOMER_CHOICE']);
    expect(SCOPE_KIND_CODES).toEqual(['ENTIRE_CART', 'COLLECTIONS', 'PRODUCTS']);
  });

  it('omits every optional key rather than writing a null or a default', () => {
    const compact = encodeOffer(offer());
    expect(Object.keys(compact)).toEqual(['i', 't', 'w', 'a', 'r']);
    expect(Object.keys(compact.r[0])).toEqual(['i', 't', 'r']);
  });

  it('keeps an empty COLLECTIONS scope distinguishable from ENTIRE_CART', () => {
    const empty = encodeOffer(offer({ scope: { kind: 'COLLECTIONS', ids: [] } }));
    const entire = encodeOffer(offer({ scope: { kind: 'ENTIRE_CART', ids: [] } }));
    expect(empty.y).toBe(1);
    expect(empty.c).toBeUndefined();
    expect(entire.y).toBeUndefined();
  });

  it('writes keys in a fixed order, so publishing the same offers twice is byte-identical', () => {
    const a = serializeConfig(encodeConfig([offer()]));
    const b = serializeConfig(encodeConfig([offer()]));
    expect(a).toBe(b);
  });
});

describe('encodeId', () => {
  it('reduces a GID to its bare numeric tail', () => {
    expect(encodeId(`${VARIANT_GID_PREFIX}1000000000000`, VARIANT_GID_PREFIX)).toBe(1000000000000);
    expect(encodeId(`${COLLECTION_GID_PREFIX}42`, COLLECTION_GID_PREFIX)).toBe(42);
  });

  it('saves 29 bytes per ProductVariant id', () => {
    const gid = `${VARIANT_GID_PREFIX}1000000000000`;
    expect(gid).toHaveLength(42);
    expect(String(encodeId(gid, VARIANT_GID_PREFIX))).toHaveLength(13);
  });

  it('keeps an id that is not a GID verbatim', () => {
    expect(encodeId('v-mug', VARIANT_GID_PREFIX)).toBe('v-mug');
  });

  it('keeps a bare numeric id as a string, so the mapping stays injective', () => {
    // Were this encoded as a number it would decode back as a GID.
    expect(encodeId('1000000000000', VARIANT_GID_PREFIX)).toBe('1000000000000');
  });

  it('keeps a tail with a leading zero verbatim, because the digits would not survive', () => {
    expect(encodeId(`${VARIANT_GID_PREFIX}0123`, VARIANT_GID_PREFIX)).toBe(
      `${VARIANT_GID_PREFIX}0123`
    );
  });

  it('keeps a tail past Number.MAX_SAFE_INTEGER verbatim', () => {
    // The Function host hands JSON numbers to Wasm as f64; a larger id would
    // be rounded on the way in and silently target the wrong variant.
    expect(encodeId(`${VARIANT_GID_PREFIX}9007199254740991`, VARIANT_GID_PREFIX)).toBe(
      9007199254740991
    );
    expect(encodeId(`${VARIANT_GID_PREFIX}9007199254740993`, VARIANT_GID_PREFIX)).toBe(
      `${VARIANT_GID_PREFIX}9007199254740993`
    );
  });

  it('does not confuse one resource type for another', () => {
    expect(encodeId(`${VARIANT_GID_PREFIX}5`, COLLECTION_GID_PREFIX)).toBe(
      `${VARIANT_GID_PREFIX}5`
    );
  });
});

describe('encodeConfig', () => {
  it('encodes an empty offer set', () => {
    expect(serializeConfig(encodeConfig([]))).toBe('{"v":1,"o":[]}');
  });

  it('preserves offer and tier order', () => {
    const compact = encodeConfig([offer({ id: 'b' }), offer({ id: 'a' })]);
    expect(compact.o.map((o) => o.i)).toEqual(['b', 'a']);
  });

  it('rejects an enum value it does not know rather than writing a wrong code', () => {
    const bad = offer({ trigger: 'WEIGHT' as never });
    expect(() => encodeConfig([bad])).toThrow(/unknown trigger/);
  });
});

describe('encodeSharded', () => {
  const many = Array.from({ length: 5 }, (_, i) => offer({ id: `o${i}` }));

  it('produces one shard, with no shard header, when everything fits', () => {
    const shards = encodeSharded(many);
    expect(shards).toHaveLength(1);
    expect(shards[0].k).toBeUndefined();
    expect(shards[0].n).toBeUndefined();
  });

  it('stamps index and count on every shard once there is more than one', () => {
    const shards = encodeSharded(many, { limit: 140, maxShards: 8 });
    expect(shards.length).toBeGreaterThan(1);
    shards.forEach((shard, i) => {
      expect(shard.k).toBe(i);
      expect(shard.n).toBe(shards.length);
    });
  });

  it('keeps every shard, header included, inside the limit', () => {
    for (const limit of [120, 140, 200, 400]) {
      for (const shard of encodeSharded(many, { limit, maxShards: 8 })) {
        expect(byteLength(serializeConfig(shard))).toBeLessThanOrEqual(limit);
      }
    }
  });

  it('preserves offer order across the shard boundary', () => {
    const shards = encodeSharded(many, { limit: 140, maxShards: 8 });
    expect(shards.flatMap((s) => s.o.map((o) => o.i))).toEqual(many.map((o) => o.id));
  });

  it('refuses rather than silently dropping offers when the shard budget is exhausted', () => {
    expect(() => encodeSharded(many, { limit: 140, maxShards: 2 })).toThrow(/shards/);
  });

  it('refuses when a single offer does not fit in one shard', () => {
    expect(() => encodeSharded(many, { limit: 30 })).toThrow(/single offer does not fit/);
  });

  it('defaults to at most four shards, leaving 24,000 bytes of input budget for the cart', () => {
    expect(MAX_SHARDS).toBe(4);
  });

  it('shards an already-compact config identically to sharding the verbose one', () => {
    const verbose = encodeSharded(many, { limit: 140, maxShards: 8 });
    const compact = shardCompactOffers(encodeConfig(many).o, { limit: 140, maxShards: 8 });
    expect(compact).toEqual(verbose);
  });
});
